export interface SampleEssay {
  id: string;
  label: string;
  description: string;
  text: string;
}

export const SAMPLE_ESSAYS: SampleEssay[] = [
  {
    id: "ai-100",
    label: "Sample: 100% AI Generated",
    description: "Generated by an RLHF-tuned LLM with low perplexity and cliché transitions.",
    text: `Delving into the multifaceted realm of modern socioeconomic paradigms, it becomes unequivocally clear that the interplay between technology and commerce is profound. Furthermore, the synergistic effects of these domains have catalyzed a paradigm shift in operational methodologies across global enterprises. In conclusion, traversing the complex landscape of digital transformation requires a robust framework of strategic agility.`,
  },
  {
    id: "human-100",
    label: "Sample: 100% Human Essay",
    description: "Authentic human prose with high burstiness, informal phrasing, and unique sentence rhythm.",
    text: `When I started looking at the data from the last quarter, the drop in local manufacturing jobs really stood out to me. It's not just about buying new software; it's about changing how people actually work on the shop floor every single day. My uncle worked at the plant for twenty years before they automated the line, and he always said that machines never notice when a bolt gets jammed until it's too late.`,
  },
  {
    id: "hybrid-polished",
    label: "Sample: AI-Polished Hybrid",
    description: "Human original draft with AI-inserted transition phrases and polished vocabulary.",
    text: `We initially set out to explore how urban housing prices impact low-income families in major metro areas. Delving into the empirical data, it becomes unequivocally clear that rising rent costs directly correlate with increased commute times for essential workers. However, talking to real tenants revealed stories that raw statistics simply cannot capture.`,
  },
  {
    id: "esl-writer",
    label: "Sample: ESL Writer (False Positive Test)",
    description: "Non-native speaker text using formal academic vocabulary that triggers generic AI detectors.",
    text: `In my country, the education system puts strong emphasis on formal examinations and strict vocabulary usage. Therefore, it is important to state that learning English as a secondary language forces students to rely heavily on structured transition words. Although some phrasing may appear rigid, every single sentence was crafted independently through dictionary lookup.`,
  },
];
